version: '3'
services:

  ghost:
    image: ghost:1-alpine
    environment:
      - database__client=mysql
      - database__connection__database=ghost
      - database__connection__host=db
      - database__connection__user=root
      - database__connection__password=senhaDoSql      
    networks:
      - my-network
    ports:
      - 2368:2368
    restart: always
    depends_on: [db]

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=senhaDoSql
    networks:
      - my-network
    restart: always
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

networks:
  my-network:  
